sudo: false
language: rust
cache: cargo
rust:
  - nightly
# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

before_script:
  - export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH
  - export PATH=$HOME/.cargo/bin:$PATH
  - which cargo-coveralls || cargo install cargo-travis
  - which rustfmt || cargo install rustfmt-nightly

script:
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test
  - cargo doc

after_success:
# measure code coverage and upload to coveralls.io
  - cargo coveralls
