[package]
name = "fluent"
description = """
A localization library designed to unleash the entire expressive power of
natural language translations.
"""
version = "0.1.2"
authors = [
    "Zibi Braniecki <gandalf@mozilla.com>",
    "Staś Małolepszy <stas@mozilla.com>"
]
homepage = "http://www.projectfluent.org"
license = "Apache-2.0/MIT"
repository = "https://github.com/projectfluent/fluent-rs"
readme = "README.md"
keywords = ["localization", "l10n"]
categories = ["localization", "internationalization"]

[dependencies]
getopts = "0.2.15"
ansi_term = "0.10.2"
fluent-locale = "0.3.1"

[dev-dependencies]
glob = "0.2.11"
