[package]
name = "fluent"
version = "0.0.1"
authors = [
    "Zibi Braniecki <gandalf@mozilla.com>",
    "Staś Małolepszy <stas@mozilla.com>"
]

[dependencies]
itertools = { git = "https://github.com/bluss/rust-itertools" }
getopts = "0.2.14"

[dev-dependencies]
glob = "0.2.11"
