[package]
name = "fluent-syntax"
description = """
Parser/Serializer tools for Fluent Syntax. 
"""
version = "0.1.1"
authors = [
    "Zibi Braniecki <gandalf@mozilla.com>",
    "Staś Małolepszy <stas@mozilla.com>"
]
homepage = "http://www.projectfluent.org"
license = "Apache-2.0/MIT"
repository = "https://github.com/projectfluent/fluent-rs"
readme = "README.md"
keywords = ["localization", "l10n", "i18n", "intl", "internationalization"]
categories = ["localization", "internationalization"]

[dependencies]
annotate-snippets = {version = "0.1", features = ["color"]}

[dev-dependencies]
glob = "0.2"
